# permissions for end users to view openstackbaremetalsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstackbaremetalset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-baremetal-operator
    app.kubernetes.io/part-of: openstack-baremetal-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstackbaremetalset-viewer-role
rules:
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackbaremetalsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackbaremetalsets/status
  verbs:
  - get
