apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: openstack-baremetal-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OpenStackBaremetalSet is the Schema for the openstackbaremetalsets
        API
      displayName: OpenStack BaremetalSet
      kind: OpenStackBaremetalSet
      name: openstackbaremetalsets.baremetal.openstack.org
      version: v1beta1
    - description: OpenStackProvisionServer used to serve custom images for baremetal
        provisioning with Metal3
      displayName: OpenStackProvisionServer
      kind: OpenStackProvisionServer
      name: openstackprovisionservers.baremetal.openstack.org
      version: v1beta1
  description: An operator for handling baremetal provisioning concerns for OpenStack
  displayName: OpenStack Baremetal Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cn-openstack
  - openstack
  links:
  - name: Openstack Baremetal Operator
    url: https://openstack-baremetal-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
